[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/introduction.html"
  status = 302

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
